test:
  api_key: api-key
  site: test-site
  webhook_user: test-user
  webhook_password: password
development:
  api_key: <%= ENV["CHARGEBEE_API_KEY"] %>
  site: <%= ENV["CHARGEBEE_SITE"] %>
  webhook_user: test-user
  webhook_password: password
production:
  api_key: <%= ENV["CHARGEBEE_API_KEY"] %>
  site: <%= ENV["CHARGEBEE_SITE"] %>
  webhook_user: <%= ENV["CHARGEBEE_WEBHOOK_USER"] %>
  webhook_password: <%= ENV["CHARGEBEE_WEBHOOK_PASS"] %>